-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            popups = true,
            xray = false,
        },
        dim_inactive = false,
        dim_strength = 0.1,
        rounding = 6,
        shadow = {
            offset = "2 1",
            range = 6,
        },
    },
    general = {
        allow_tearing = true,
        border_size = 0,
        gaps_in = 3,
        gaps_out = 15,
        snap = {
            enabled = true,
            respect_gaps = true,
        },
    },
    gestures = {
        workspace_swipe_forever = false,
    },
    input = {
        touchpad = {
            natural_scroll = false,
        },
    },
    misc = {
        animate_manual_resizes = true,
        animate_mouse_windowdragging = true,
    },
})
